# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-18 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.FileField(blank=True, null=True, upload_to='')),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('subhead', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('dis', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('dis', models.CharField(blank=True, max_length=200, null=True)),
                ('fee', models.CharField(blank=True, max_length=200, null=True)),
                ('main_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebSite.Main_course')),
            ],
        ),
    ]
