# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-30 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_course',
            name='long_dis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
