# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-30 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0002_sub_course_long_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_course',
            name='long_dis',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
