# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0004_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_content',
            name='sub_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebSite.Sub_course'),
        ),
    ]
