# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-31 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0019_institite_profile_map'),
        ('WebSite', '0006_student_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('messege', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebSite.Sub_course')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile')),
            ],
        ),
    ]
