# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-31 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0007_student_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_query',
            old_name='messege',
            new_name='message',
        ),
    ]
