# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-31 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0009_director_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_course',
            name='image',
        ),
    ]
