# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-01 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0010_remove_main_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_we_are', models.TextField(blank=True, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='')),
                ('why_join_us', models.TextField(blank=True, null=True)),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
                ('our_vision', models.TextField(blank=True, null=True)),
                ('our_mission', models.TextField(blank=True, null=True)),
                ('mission_tag_line', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Counter_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Welcome_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='director_profile',
            name='director_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
