# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-01 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0011_auto_20190601_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter_data',
            old_name='value',
            new_name='value1',
        ),
        migrations.RemoveField(
            model_name='counter_data',
            name='name',
        ),
        migrations.AddField(
            model_name='counter_data',
            name='value2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counter_data',
            name='value3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counter_data',
            name='value4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
