# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-01 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0012_auto_20190601_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome_content',
            name='why_choose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
