# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0013_welcome_content_why_choose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Feddback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
