# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-02 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0014_faculty_feddback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_gallery_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('Title', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
