# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-01 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Frontdesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libraryfine', models.CharField(blank=True, max_length=20, null=True)),
                ('latefeefine', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library_Issue_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(blank=True, max_length=50, null=True)),
                ('Due', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('Return', models.CharField(blank=True, max_length=50, null=True)),
                ('late_fee', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master_book_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='')),
                ('book_title', models.CharField(max_length=100, null=True)),
                ('subbook_title', models.CharField(max_length=100, null=True)),
                ('ISBN', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('editor', models.CharField(max_length=100, null=True)),
                ('series', models.CharField(max_length=100, null=True)),
                ('publication_year', models.CharField(max_length=100, null=True)),
                ('edition', models.CharField(max_length=100, null=True)),
                ('pages', models.CharField(max_length=100, null=True)),
                ('copies', models.CharField(max_length=100, null=True)),
                ('ave_copy', models.CharField(max_length=100, null=True)),
                ('created_date', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master_catbook_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_date', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master_E_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('book', models.FileField(null=True, upload_to='')),
                ('created_date', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LibraryPanel.Master_catbook_data')),
            ],
        ),
        migrations.CreateModel(
            name='Master_subcatbook_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_date', models.CharField(max_length=20, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryPanel.Master_catbook_data')),
            ],
        ),
        migrations.AddField(
            model_name='master_e_book',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LibraryPanel.Master_subcatbook_data'),
        ),
        migrations.AddField(
            model_name='master_book_data',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LibraryPanel.Master_catbook_data'),
        ),
        migrations.AddField(
            model_name='master_book_data',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LibraryPanel.Master_subcatbook_data'),
        ),
        migrations.AddField(
            model_name='library_issue_book',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryPanel.Master_book_data'),
        ),
        migrations.AddField(
            model_name='library_issue_book',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontdesk.Front_student_data'),
        ),
    ]
