# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryPanel', '0003_auto_20190428_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_book_data',
            name='ins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
    ]
