# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-28 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0013_auto_20190428_1011'),
        ('Frontdesk', '0002_front_student_data_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_all_uploaded_document',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='front_call_logs',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='front_cancal_addmission_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='front_document_files',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='front_enquiry_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='front_student_course_batch_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='front_student_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='front_student_fee_installment_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='front_student_fee_type_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='front_student_pay_fee',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='institute_number',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='invoice_number_generate',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='notification_on_panel',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='todays_follow_up_date',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
    ]
