# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontdesk', '0005_auto_20190504_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front_enquiry_data',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_enquiry_data',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_enquiry_data',
            name='graduation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
