# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-05 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontdesk', '0006_auto_20190504_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_document_files',
            name='doc_file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
