# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-02 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0002_user_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_sms_settings_data',
            name='sms_emp_bday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_emp_bday', to='Institute.SMSTemplate'),
        ),
        migrations.AlterField(
            model_name='auto_sms_settings_data',
            name='sms_fee_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_fee_reminder', to='Institute.SMSTemplate'),
        ),
        migrations.AlterField(
            model_name='auto_sms_settings_data',
            name='sms_new_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_new_add', to='Institute.SMSTemplate'),
        ),
        migrations.AlterField(
            model_name='auto_sms_settings_data',
            name='sms_new_ts_asign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_new_ts_asign', to='Institute.SMSTemplate'),
        ),
        migrations.AlterField(
            model_name='auto_sms_settings_data',
            name='sms_student_bday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_student_bday', to='Institute.SMSTemplate'),
        ),
        migrations.AlterField(
            model_name='auto_sms_settings_data',
            name='sms_student_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_student_fee', to='Institute.SMSTemplate'),
        ),
    ]
