# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-04 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0004_nowsms_sms_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_pack',
            name='paid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
