# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0006_visiteduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_employee_data',
            name='join_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
