# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-08 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0010_visiteduser_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_employee_data',
            name='office_in_time',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='master_employee_data',
            name='office_out_time',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
