# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-28 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0011_auto_20190108_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_batch_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='master_course_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='master_employee_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='master_fee_type_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='master_fee_type_packege_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='master_holiday_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='master_installment_last_date',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='master_make_installment_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='master_medium_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='master_subject_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='user_management',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
    ]
