# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0015_nowstudents_student_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_sms_settings_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='master_sender_id',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
    ]
