# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0016_auto_20190505_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_designation_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
        migrations.AddField(
            model_name='master_medium_data',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Institite_profile'),
        ),
    ]
