# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-05 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0017_auto_20190505_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto_sms_settings_data',
            name='ins',
        ),
        migrations.RemoveField(
            model_name='master_designation_data',
            name='ins',
        ),
        migrations.RemoveField(
            model_name='master_medium_data',
            name='ins',
        ),
        migrations.RemoveField(
            model_name='master_sender_id',
            name='ins',
        ),
        migrations.RemoveField(
            model_name='smstemplate',
            name='ins',
        ),
    ]
