# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-07 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0018_auto_20190505_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='institite_profile',
            name='map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
